export const color = [
  { name: "Red", bgClass: "bg-red" },
  { name: "Blue", bgClass: "bg-blue" },
  { name: "Green", bgClass: "bg-green" },
  { name: "Yellow", bgClass: "bg-yellow" },
  { name: "Orange", bgClass: "bg-orange" },
  { name: "Purple", bgClass: "bg-purple" },
  { name: "Pink", bgClass: "bg-pink" },
  { name: "Brown", bgClass: "bg-brown" },
  { name: "Gray", bgClass: "bg-gray" },
  { name: "Black", bgClass: "bg-black" },
  { name: "White", bgClass: "bg-white" },
  { name: "Cyan", bgClass: "bg-cyan" },
  { name: "Magenta", bgClass: "bg-magenta" },
  { name: "Teal", bgClass: "bg-teal" },
  { name: "Lavender", bgClass: "bg-lavender" },
  { name: "Indigo", bgClass: "bg-indigo" },
  { name: "Maroon", bgClass: "bg-maroon" },
  { name: "Olive", bgClass: "bg-olive" },
  { name: "Coral", bgClass: "bg-coral" },
  { name: "Turquoise", bgClass: "bg-turquoise" },
];
